version: '2'
services:
    kenyaemr:
        container_name: kenyaemr
        build: kenyaemr
        depends_on:
            - kenyaemr-mysql
        image: kenyaemr:latest
        env_file: main.env
        volumes:
             - data:./openmrs:/root/.OpenMRS
        restart: unless-stopped
        ports:
            - 8080:8080
    kenyaemr-mysql:
        build: mysql
        container_name: kenyaemr-mysql
        networks:
            - network
        volumes:
            - data:/opt/kenyaemr/data
        hostname: isanteplus-mysql
        restart: unless-stopped
        ports: 
            - 3306:3306
networks:
    network:
volumes:
    data: